# Generated by Django 4.1 on 2022-08-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=120),
        ),
        migrations.AlterField(
            model_name='country',
            name='slug',
            field=models.SlugField(max_length=120),
        ),
    ]
