# Generated by Django 4.0.4 on 2022-12-24 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_category_slug_alter_country_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductRate',
        ),
    ]
