# Generated by Django 4.1 on 2023-04-22 10:01

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_seller_product_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='shipping_origin',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
