version: '3.9'

services:

  backend:

    build: .
    command: sh docker-entrypoint.sh


    container_name: backend
    restart: on-failure

    ports:
      - 8000:8000

    volumes:
      - .:/backend

    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.production
    
    depends_on:
      - db
      - redis

  db:
    image: postgres:12

    container_name: database
    restart: on-failure

    ports: 
          - "5432:5432"

    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

  redis:
    image: redis:6.2-alpine
    
    ports:
      - 6379:6379

    restart: always