# Generated by Django 4.1 on 2023-04-30 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_remove_chat_creator_remove_chat_member_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='code',
            field=models.CharField(default=12, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chat',
            name='code',
            field=models.CharField(max_length=20),
        ),
    ]
