# Generated by Django 4.2 on 2023-05-11 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0002_remove_forum_allowed_members_forumpurchase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumanswer',
            name='is_correct_answer',
            field=models.BooleanField(default=False),
        ),
    ]
