# Generated by Django 4.0.4 on 2022-12-23 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_forumrate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ForumRate',
        ),
    ]
