# Generated by Django 4.0.4 on 2022-12-29 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_delete_forumrate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ForumComment',
        ),
    ]
