# Generated by Django 4.1 on 2022-08-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='token',
            field=models.CharField(default='A', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
