# Generated by Django 4.1 on 2022-08-21 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_rate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rate',
            new_name='VendorRate',
        ),
    ]
